### ISSUE TITLE
improve README

### ISSUE THREAD

**Issue by qpab7722** [ekdud014/OSS_pacman#19]
i think we need a explain of necessary libraries.
Also it will be comfortable if we have .exe file to check and play it.

**Comment by qpab7722** [comment]
and it needs to remove '-' front of keys

**Comment by qpab7722** [comment]
needs  explain of  restart with 'space'

**Comment by yeonsoy** [comment]
## Original
https://github.com/patriciateroltolsa/Pacman

## Library
We use library [SDL](https://www.libsdl.org/) 1.2 (with SDL Mixer) & [OpenGL](https://www.opengl.org/)

## Execution environment
It works in compiler C++11. (If you use Visual Studio, you must use Visual Studio 2011 or later.) 
We use Windows 7 ([Visual Studio 2013](https://msdn.microsoft.com/library/dd831853(v=vs.120).aspx)) & Windows 10 ([Visual Studio 2017](https://www.visualstudio.com/ko-kr/productinfo/vs2017-system-requirements-vs)) & Mac OS X ([Xcode](https://developer.apple.com/xcode/))

## Contributing

- Fork this project.
- Create your branch
git checkout -b 'branch_name' or git branch 'branch_name' & git checkout 'branch_name'
- Commit your changes: git commit -m 'commit message'
- Push to the branch: git push origin branch_name
- Lastly, **Pull requests** for us project!
