### ISSUE TITLE
Animation of pacman's mouth

### ISSUE THREAD

**Issue by SojeongLee** [ekdud014/OSS_pacman#24]
Pacman's mouth should move like eating a dot.

**Comment by yeonsoy** [comment]
It seems that 2D and 3D should be implemented differently.

**Comment by SojeongLee** [comment]
Yes, you are right.
I think 3D screen don't need to draw whole pacman because 3D screen will be first person view,
so I think there(3D screen) need another draw pacman function that draw pacman's head.
